import { useState } from "react";
import { CLASS_LABELS, TIER_LABELS } from "../../../shared/labels.ts";
import type { AlertRecord, SatEvent } from "../../../shared/types.ts";
import { api, errorText, type SitrepResponse } from "../../lib/api";
import { fmtTime } from "../../lib/format";
import { useSatfire } from "../../lib/store";
import { DispatchBadge } from "../badges";
import { Section } from "../panels";

export function ReviewSection({ event }: { event: SatEvent }) {
  const { replaceEvent, reload } = useSatfire();
  const [note, setNote] = useState("");
  const [busy, setBusy] = useState(false);
  const [err, setErr] = useState<string | null>(null);
  const [result, setResult] = useState<{ eventId: string; alert: AlertRecord | null } | null>(null);
  const r = event.review;
  const shownResult = result?.eventId === event.id ? result : null;

  const submit = async (decision: "confirm" | "reject") => {
    setBusy(true);
    setErr(null);
    try {
      const res = await api.review(event.id, event.dataset, decision, note.trim());
      setResult({ eventId: event.id, alert: res.alert });
      replaceEvent(res.event);
      setNote("");
      reload();
    } catch (e) {
      setErr(errorText(e));
    } finally {
      setBusy(false);
    }
  };

  return (
    <Section
      title="Operator review"
      right={event.classification.needsReview && !r ? <span className="font-mono text-[10px] uppercase text-sky-900">needs review</span> : undefined}
    >
      {r ? (
        <div className="text-xs text-ink">
          <span className={`font-semibold ${r.decision === "confirm" ? "text-emerald-800" : "text-red-800"}`}>
            {r.decision === "confirm" ? "Confirmed" : "Rejected"}
          </span>{" "}
          as {CLASS_LABELS[r.label]} by <span className="font-mono">{r.by}</span> at <span className="font-mono">{fmtTime(r.at)}</span>
          {r.note && <div className="mt-1 text-mute">Note: {r.note}</div>}
          <div className="mt-1 text-[11px] text-mute">
            Resulting tier: {event.classification.tier ? TIER_LABELS[event.classification.tier] : "none"} — {event.classification.tierReason}
          </div>
        </div>
      ) : (
        <div className="space-y-2">
          {event.classification.reviewReason && <div className="text-[11px] text-sky-900">Reason: {event.classification.reviewReason}</div>}
          <label className="block text-[11px] text-mute" htmlFor={`note-${event.id}`}>
            Note (optional)
          </label>
          <textarea
            id={`note-${event.id}`}
            value={note}
            onChange={(e) => setNote(e.target.value)}
            rows={2}
            className="w-full rounded-sm border border-rule bg-paper p-2 text-xs text-ink focus:border-ink focus:outline-none"
            placeholder="What did you check?"
          />
          <div className="flex flex-wrap gap-2">
            <button
              type="button"
              disabled={busy}
              onClick={() => submit("confirm")}
              className="border border-emerald-800 bg-emerald-800 px-3 py-1.5 text-xs font-semibold text-white hover:bg-emerald-900 disabled:opacity-50"
            >
              Confirm {CLASS_LABELS[event.classification.label]}
            </button>
            <button
              type="button"
              disabled={busy}
              onClick={() => submit("reject")}
              className="border border-red-800 px-3 py-1.5 text-xs font-semibold text-red-800 hover:bg-red-50 disabled:opacity-50"
            >
              Reject
            </button>
          </div>
          <div className="text-[10.5px] text-faint">
            Decisions are written to the gold-labelled set. Confirming an Alert raises it to Code Red and generates a SITREP.
          </div>
        </div>
      )}
      {err && <div className="mt-2 text-xs text-red-800">Review failed: {err}</div>}
      {shownResult && (
        <div className="mt-2 rounded bg-ink/5 p-2 text-[11px]">
          {shownResult.alert ? (
            <div className="flex flex-wrap items-center gap-2">
              <span>
                Alert <span className="font-mono">{shownResult.alert.id}</span> ({shownResult.alert.kind.replace("_", " ")}) recorded — dispatch:
              </span>
              <DispatchBadge status={shownResult.alert.dispatch.status} />
              {shownResult.alert.dispatch.lastError && <span className="text-red-800">{shownResult.alert.dispatch.lastError}</span>}
            </div>
          ) : (
            <span className="text-mute">No alert generated by this decision.</span>
          )}
        </div>
      )}
    </Section>
  );
}

export function SitrepSection({ event }: { event: SatEvent }) {
  const [busy, setBusy] = useState(false);
  const [err, setErr] = useState<string | null>(null);
  const [sitrep, setSitrep] = useState<(SitrepResponse & { eventId: string }) | null>(null);
  const [copied, setCopied] = useState(false);
  const shown = sitrep?.eventId === event.id ? sitrep : null;

  const generate = async () => {
    setBusy(true);
    setErr(null);
    setCopied(false);
    try {
      setSitrep({ ...(await api.sitrep(event.id, event.dataset)), eventId: event.id });
    } catch (e) {
      setErr(errorText(e));
    } finally {
      setBusy(false);
    }
  };

  return (
    <Section
      title="Situation report"
      right={
        <button
          type="button"
          onClick={generate}
          disabled={busy}
          className="border border-ink px-2.5 py-1 font-mono text-[11px] uppercase hover:bg-ink hover:text-paper disabled:opacity-50"
        >
          {busy ? "Generating…" : shown ? "Regenerate" : "Generate SITREP"}
        </button>
      }
    >
      {err && <div className="text-xs text-red-800">SITREP failed: {err}</div>}
      {shown ? (
        <>
          <div className="mb-1 flex flex-wrap items-center gap-2 text-[11px]">
            <span className="border border-rule bg-ink/5 px-1.5 py-0.5 font-mono text-[10px] uppercase">
              {shown.phrasing === "llm" ? "LLM-phrased (facts checked against template)" : "Template"}
            </span>
            <span className="text-mute">{shown.note}</span>
          </div>
          <pre className="max-h-96 overflow-auto whitespace-pre-wrap rounded bg-ink/5 p-3 font-mono text-[11px] leading-relaxed text-ink scroll-thin">
            {shown.text}
          </pre>
          <button
            type="button"
            onClick={() =>
              navigator.clipboard
                ?.writeText(shown.text)
                .then(() => setCopied(true))
                .catch(() => setCopied(false))
            }
            className="mt-2 border border-rule px-2.5 py-1 text-xs hover:border-ink"
          >
            {copied ? "Copied" : "Copy SITREP"}
          </button>
        </>
      ) : (
        !err && (
          <div className="text-[11px] text-faint">
            Built from a fixed template (facility metadata, Dozier range, CPCB category, evidence list). An LLM may only rephrase it; on failure the raw template is used.
          </div>
        )
      )}
    </Section>
  );
}
